name: Parse FunPay Divine Orbs
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  parse:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests beautifulsoup4 pygithub fake-useragent pytz lxml playwright
          pip list | grep playwright
      - name: Install Playwright browsers
        run: python -m playwright install --with-deps
      - name: Run parser
        run: python funpay_divine_orbs_parser.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Compress JSON files
        run: |
          for file in *.json; do
            if [ -f "$file" ]; then
              gzip "$file"
              echo "Compressed $file to $file.gz"
            fi
          done
      - name: Check artifact size
        run: |
          total_size=$(du -sb *.json.gz *.html *.txt 2>/dev/null | awk '{sum+=$1} END {print sum}')
          if [ $total_size -gt 10485760 ]; then
            echo "Warning: Total artifact size ($total_size bytes) exceeds 10 MB"
          else
            echo "Total artifact size: $total_size bytes"
          fi
      - uses: actions/upload-artifact@v4
        with:
          name: parser-artifacts
          path: |
            *.json.gz
            *.html
            *.txt
          retention-days: 30
