name: Parse FunPay Prices
on:
  schedule:
    - cron: '55 * * * *'  # В начале каждого часа (00:00 UTC = 03:00 MSK)
  workflow_dispatch:  # Ручной запуск через интерфейс GitHub

jobs:
  parse:
    runs-on: ubuntu-latest  # Рекомендуется вместо ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pygithub fake-useragent pytz lxml

      - name: Run parser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python funpay_divine_orbs_parser.py

      - name: Compress JSON artifacts
        run: |
          for file in *.json; do
            if [ -f "$file" ]; then
              gzip "$file"
              echo "Compressed $file to $file.gz"
            fi
          done

      - name: Clean up outdated JSON files
        run: |
          for file in prices_poe_*_2025-05.json.gz prices_poe2_*_2025-05.json.gz; do
            if [ -f "$file" ]; then
              rm "$file"
              echo "Removed outdated file: $file"
            fi
          done

      - name: Check artifact size
        run: |
          total_size=$(du -sb *.json.gz *.html *.txt 2>/dev/null | awk '{sum+=$1} END {print sum}')
          if [ $total_size -gt 10485760 ]; then
            echo "Warning: Total artifact size ($total_size bytes) exceeds 10 MB"
          else
            echo "Total artifact size: $total_size bytes"
          fi

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parser-artifacts
          path: |
            *.json.gz
            *.html
            *.txt
          retention-days: 30
